name: k6 run getListUser-loadtest
on: [push, pull_request]
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: get Posts Detail
        uses: grafana/k6-action@v0.2.0
        with:
          filename: getListUser-loadtest.js
#           flags: --vus 1 --duration 1s
#           cloud: true
#           token: ${{ secrets.K6_CLOUD_API_TOKEN }}
